apiVersion: v1
kind: Service
metadata:
  labels:
    app: probe-demo
  name: probe-demo-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: probe-demo
  type: ClusterIP
